In [7]:
import numpy as np

To create array

In [8]:
a= np.array([15,20,65])
a

array([15, 20, 65])

To check the type of any array

In [3]:
type(a)

numpy.ndarray

To check the Dimension of any array

In [5]:
a.ndim

1

To Create 2D array

In [4]:
b=np.array([[1,5,7],[2,4,6]])

To check size of array and check the elements in array

In [5]:
np.size(b)

6

To check the row and column

In [16]:
a.shape

(3,)

In [17]:

b.shape

(2, 3)

to check the datatype of any array

In [10]:
a.dtype

dtype('int32')

# Array Slicing

In [14]:
arra=[1,2,3,45,6,6,7,7,5,4,32,]
print(arra[:8])

[1, 2, 3, 45, 6, 6, 7, 7]


# Reshape

Reshape will help you to create a long size list into small list

In [13]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a.reshape([4,3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Iterating 2D Array

In [16]:
xx=np.array([[1, 2, 3], [4, 5, 6]])

for x in xx:
  print(x)

[1 2 3]
[4 5 6]


# Array Concatenation (JOIN)

In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [19]:
arr=np.concatenate((arr1,arr2))

In [20]:
arr

array([1, 2, 3, 4, 5, 6])

In [21]:

arr3 = np.array([[1, 2], [3, 4]])

arr4 = np.array([[5, 6], [7, 8]])

In [26]:
arr5=np.concatenate((arr3,arr4))

In [27]:
arr5

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Joining Arrays Using Stack Functions

In [40]:
arr6=np.stack((arr3,arr4),axis=1)

In [41]:
arr6

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])